# 🚀 Expert Shopify Theme Check - VS Code Optimized Pro
root: .

# Disable problematic checks that cause VS Code issues
SpaceInsideBraces:
  enabled: false

RequiredLayoutThemeObject:
  enabled: false

LiquidTag:
  enabled: false

UnknownFilter:
  enabled: false

# Enable important performance checks
DeprecatedFilter:
  enabled: true

ImgWidthAndHeight:
  enabled: true

AssetSizeCSS:
  enabled: true
  threshold_in_bytes: 100000

AssetSizeJavaScript:
  enabled: true
  threshold_in_bytes: 100000

# Enable accessibility checks
ImgLazyLoading:
  enabled: true

# Enable SEO checks
MetaViewport:
  enabled: true

HtmlLang:
  enabled: true

# Security checks
ContentForHeaderModification:
  enabled: false

# Performance checks
RemoteAsset:
  enabled: true

# Liquid syntax checks
LiquidHTMLInLiquidTag:
  enabled: true

SyntaxError:
  enabled: true

# Exclude comprehensive list
exclude:
  - "backup*/**"
  - "node_modules/**"
  - ".github/**"
  - "*.sh"
  - "*.md"
  - "*.log"
  - ".git/**"
  - ".vscode/**"
  - "tmp/**"
  - ".shopify/**"
